kind: pipeline
type: docker
name: default
steps:
  - name: install
    image: node:14
    commands:
      - yarn install --frozen-lockfile
  - name: build
    image: node:14
    commands:
      - unset CI
      - yarn workspace client build
  - name: publish
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ccacc/1sc-project
      auto_tag: true
  - name: deploy
    image: docker/compose
    commands:
      - docker pull ccacc/1sc-project
      - docker-compose up -d
    environment:
      KEYCLOAK_URL:
        from_secret: keycloak_url
      KEYCLOAK_REALME:
        from_secret: keycloak_realme
      POSTGRES_HOST:
        from_secret: postgres_host
      POSTGRES_DB:
        from_secret: postgres_db
      POSTGRES_USER:
        from_secret: postgres_user
      POSTGRES_PASSWORD:
        from_secret: postgres_password
      POSTGRES_PORT:
        from_secret: postgres_port
    volumes:
      - name: docker
        path: /var/run/docker.sock

trigger:
  branch:
    - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

