version: '3.8'

services:
  1sc-project:
    image: ccacc/1sc-project
    container_name: 1sc-project
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_REALME=${KEYCLOAK_REALME}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    depends_on:
      - postgres
    networks:
      - docker_proxy
  
  postgres:
    image: postgres
    container_name: postgres
    environment: 
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - docker_proxy

networks:
  docker_proxy:
    external: true
